- type: loadoutGroup
  id: SecurityHead
  abstract: true

- type: loadoutGroup
  id: SecurityGlasses
  abstract: true

- type: loadoutGroup
  id: SecurityMask
  abstract: true

- type: loadoutGroup
  id: SecurityNeck
  abstract: true
  loadouts:
  - SecStar

- type: loadoutGroup
  id: SecurityGloves
  abstract: true

- type: loadoutGroup
  id: SecurityJumpsuit
  abstract: true

- type: loadoutGroup
  id: SecurityBackpack
  abstract: true
  loadouts:
  - SecurityBackpack
  - SecuritySatchel
  - SecurityDuffel

- type: loadoutGroup
  id: SecurityPDA
  abstract: true

- type: loadoutGroup
  id: SecurityBelt
  abstract: true
  loadouts:
  - SecurityBelt
  - SecurityWebbing

- type: loadoutGroup
  id: SecurityOuterClothing
  abstract: true

- type: loadoutGroup
  id: SecurityShoes
  abstract: true
  loadouts:
  - JackBoots
  - SecurityWinterBoots

- type: loadoutGroup
  id: SecurityTrinkets
  abstract: true
