using Content.Client._Carpmosia.UserInterface.Systems.Emotes.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Carpmosia.UserInterface.Systems.Emotes.Windows;

[GenerateTypedNameReferences]
public sealed partial class EmotesWindow : DefaultWindow
{
    public EmotesWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetButtons(IEnumerable<EmoteButton> buttons)
    {
        EmotesGrid.RemoveAllChildren();
        foreach (var button in buttons)
        {
            EmotesGrid.AddChild(button);
        }
    }
}
