using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Client.Placement;

namespace Content.Client.MappingHelper;

[GenerateTypedNameReferences]
public sealed partial class MappingHelperWindow : DefaultWindow
{
    [Dependency] private readonly IPrototypeManager _proto = default!;
    [Dependency] private readonly IPlacementManager _place = default!;

    private static readonly (string, int, string[])[] Buttons = [
    ("Walls", 4, [
        "WallSolidDiagonal", "WallReinforcedDiagonal",
        "WallSolidDiagonalRust", "WallReinforcedDiagonalRust",
        "WallSolid", "WallReinforced",
        "WallSolidRust", "WallReinforcedRust"
    ]),
    ("Windows", 3, [
        "GrilleDiagonal", "WindowDiagonal", "ReinforcedWindowDiagonal",
        "Grille", "Window", "ReinforcedWindow",
    ]),
    ("Pipes", 2, [
        "GasPipeTJunction",  "GasPipeBend",
        "GasPipeFourway", "GasPipeStraight",
    ]),
    ("Atmos", 2, [
        "GasVentPump",  "GasVentScrubber",
        "AirAlarm"
    ]),
    ("Atmos", 2, [
        "CableApcExtension",  "CableMV",
        "CableHV", "APCBasic"
    ]),
    ("Light", 2, [
        "Poweredlight",  "PoweredSmallLight",
    ]),
    ("Nothing", 2, [
        "ChairOfficeDark", "WaterCooler", "Chair", "Rack", "WeldingFuelTankFull", "WaterTankFull", "ComfyChair"
    ]),
    ("Nothing", 2, [
        "RailingCorner", "Railing", "RailingRound", "RailingCornerSmall"
    ]),
    ("Nothing", 2, [
        "DisposalPipe", "DisposalBend",
        "DisposalRouterFlipped", "DisposalRouter",
        "DisposalJunctionFlipped", "DisposalJunction",
        "DisposalUnit", "MailingUnit","DisposalTrunk",
    ])
    ];

    public MappingHelperWindow()
    {
        RobustXamlLoader.Load(this);

        foreach ((var section, var cols, var items) in Buttons)
        {
            var box = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical };

            box.AddChild(new Label { Text = section });

            var c = new PanelContainer();
            c.StyleClasses.Add("LowDivider");
            box.AddChild(c);

            var g = new GridContainer { Columns = cols };

            foreach (string item in items)
            {
                var but = new ContainerButton { };
                var ent = new EntityPrototypeView
                {
                    MinSize = new Vector2(64, 64),
                    Scale = new Vector2(2, 2),
                    MaxSize = new Vector2(64, 64),
                    Name = item
                };
                ent.SetPrototype(item);
                but.AddChild(ent);
                but.OnPressed += (a) =>
                {
                    var proto = _proto.Index(item);
                    _place.BeginPlacing(new()
                    {
                        EntityType = item,
                        IsTile = false,
                        TileType = 0,
                        PlacementOption = proto.PlacementMode,
                    });
                };
                g.AddChild(but);
            }
            box.AddChild(g);


            Content.AddChild(box);
        }
    }
}
