reviewers:
  defaults:
    - everything
  groups:
    everything:
      - atakku
      - imatsoup
    mapping:
      - arenaconspiracy
      - wavesneglected
    guidebook:
      - wavesneglected

files:
  '**':
    - everything
  'Resources/Maps/**':
    - mapping
  'Resources/Prototypes/Maps/**':
    - mapping
  'Resources/Prototypes/_Carpmosia/Maps/**':
    - mapping
  'Resources/Prototypes/ServerInfo/**':
    - guidebook

options:
  ignore_draft: true
  last_files_match_only: false
