- type: roleLoadout
  id: JobChemist
  groups:
  # - GroupTankHarness
  # Common groups
  # - ChemistHead
  # - ChemistGlasses
  # - ChemistMask
  # - ChemistNeck
  # - ChemistGloves
  # - ChemistJumpsuit
  # - ChemistBackpack
  # - ChemistPDA
  # - ChemistBelt
  # - ChemistOuterClothing
  # - ChemistShoes
  # Backpack fills
  # - Survival
  # - GroupSpeciesBreathTool
  # - ChemistSpecial
  # - ChemistTrinkets
