- type: roleLoadout
  id: JobChemist
  groups:
  - GroupTankHarness
  # Common groups
  - SharedClownHead
  - ChemistGlasses
  - ChemistMask
  - ChemistNeck
  - ChemistGloves
  - ChemistJumpsuit
  - SharedClownBackpack
  # - ChemistPDA
  # - ChemistBelt
  - ChemistOuterClothing
  - SharedClownShoes
  # Backpack fills
  - SurvivalMedical
  - GroupSpeciesBreathToolMedical
  # - ChemistSpecial
  - ChemistTrinkets
  - ChemistPets
