- type: roleLoadout
  id: JobChemist
  groups:
  - GroupTankHarness
  # Common groups
  - ClownHead
  - ChemistGlasses
  - ChemistMask
  - ChemistNeck
  - ChemistGloves
  - ChemistJumpsuit
  - ClownBackpack
  # - ChemistPDA
  # - ChemistBelt
  - ChemistOuterClothing
  - ClownShoes
  # Backpack fills
  - SurvivalMedical
  - GroupSpeciesBreathToolMedical
  # - ChemistSpecial
  - ChemistTrinkets
  - ChemistPets
