- type: roleLoadout
  id: JobMedicalIntern
  groups:
  - GroupTankHarness
  # Common groups
  - ClownHead
  - MedicalInternGlasses
  # - MedicalInternMask
  - MedicalInternNeck
  # - MedicalInternGloves
  - MedicalInternJumpsuit
  - ClownBackpack
  # - MedicalInternPDA
  # - MedicalInternBelt
  # - MedicalInternOuterClothing
  - ClownShoes
  # Backpack fills
  - SurvivalMedical
  - GroupSpeciesBreathToolMedical
  # - MedicalInternSpecial
  - MedicalInternTrinkets
  - MedicalInternPets
