- type: roleLoadout
  id: JobParamedic
  groups:
  - GroupTankHarness
  # Common groups
  - SharedClownHead
  - ParamedicGlasses
  - ParamedicMask
  - ParamedicNeck
  - ParamedicGloves
  - ParamedicJumpsuit
  - SharedClownBackpack
  # - ParamedicPDA
  # - ParamedicBelt
  - ParamedicOuterClothing
  - SharedClownShoes
  # Backpack fills
  - SurvivalMedical
  - GroupSpeciesBreathToolMedical
  # - ParamedicSpecial
  - ParamedicTrinkets
  - ParamedicPets
