using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._FarHorizons.Research;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._FarHorizons.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class FHResearchConsoleWindow : FancyWindow
{
    [Dependency] private IPrototypeManager _protoMan = default!;

    private HashSet<ResearchTreeNodePrototype> _allNodes = [];
    private HashSet<ProtoId<ResearchTreeTierPrototype>> _unlockedTiers = [];
    private HashSet<ProtoId<ResearchTreeNodePrototype>> _unlockedNodes = [];
    private HashSet<ProtoId<ResearchTreeNodePrototype>> _researchedNodes = [];
    private ResearchTreeNodePrototype? _selected = null;
    private List<ProtoId<ResearchTreeNodePrototype>> _queue = [];
    private Dictionary<ProtoId<ResearchTreeNodePrototype>, int> _researchProgress = [];
    private Dictionary<ProtoId<ResearchTreeNodePrototype>, float> _researchProgressPercentage => _researchProgress.ToDictionary(p => p.Key, p => (float)p.Value / _protoMan.Index(p.Key).Cost);
    private int _bankedPoints = 0;
    private bool _readonly = false;

    public Action? OnServerButtonPressed;
    public Action<ProtoId<ResearchTreeNodePrototype>>? OnResearchButtonPressed;
    public Action<ProtoId<ResearchTreeNodePrototype>>? OnRemoveQueueButtonPressed;
    public Action<ProtoId<ResearchTreeNodePrototype>>? OnQuickResearch;

    public FHResearchConsoleWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        ServerButton.OnPressed += _ => OnServerButtonPressed?.Invoke();
        TreeDisplay.OnSelectionChanged += Selected;
        TreeDisplay.OnQuickResearch += QuickResearch;
    }

    public void SetupUI(
        HashSet<ResearchTreeNodePrototype> nodes,
        HashSet<ProtoId<ResearchTreeTierPrototype>> unlockedTiers,
        HashSet<ProtoId<ResearchTreeNodePrototype>> unlockedNodes,
        HashSet<ProtoId<ResearchTreeNodePrototype>> researched,
        List<ProtoId<ResearchTreeNodePrototype>> queued,
        Dictionary<ProtoId<ResearchTreeNodePrototype>, int> progress,
        int bankedPoints,
        bool readonlyClient)
    {
        _selected = null;
        _allNodes = nodes;
        _unlockedTiers = unlockedTiers;
        _unlockedNodes = unlockedNodes;
        _researchedNodes = researched;
        _queue = queued;
        _researchProgress = progress;
        _bankedPoints = bankedPoints;
        _readonly = readonlyClient;

        BankedPointsText.Text = _bankedPoints.ToString();

        if (_readonly)
            ResearchButton.Visible = false;

        TreeDisplay.BuildTree(_allNodes, _unlockedTiers, _unlockedNodes, _researchedNodes, _researchProgressPercentage, _queue);
        Selected(_selected?.ID);
        UpdateQueue();
    }

    public void RefreshUI(
        HashSet<ProtoId<ResearchTreeTierPrototype>> unlockedTiers,
        HashSet<ProtoId<ResearchTreeNodePrototype>> unlockedNodes,
        HashSet<ProtoId<ResearchTreeNodePrototype>> researched,
        List<ProtoId<ResearchTreeNodePrototype>> queued,
        Dictionary<ProtoId<ResearchTreeNodePrototype>, int> progress,
        int bankedPoints)
    {
        _unlockedTiers = unlockedTiers;
        _unlockedNodes = unlockedNodes;
        _researchedNodes = researched;
        _queue = queued;
        _researchProgress = progress;
        _bankedPoints = bankedPoints;

        BankedPointsText.Text = _bankedPoints.ToString();

        TreeDisplay.RefreshTree(_unlockedTiers, _unlockedNodes, _researchedNodes, _researchProgressPercentage, _queue);
        Selected(_selected?.ID);
        UpdateQueue();
    }

    public void Selected(ProtoId<ResearchTreeNodePrototype>? selected)
    {
        ResearchButton.OnPressed -= ResearchNode;
        ResearchButton.OnPressed -= RemoveNodeFromQueue;
        ResearchButton.Text = Loc.GetString("research-tree-button-research");
        ResearchButton.Disabled = true;
        SelectedProgressLabel.Visible = false;

        if (selected != null)
        {
            _selected = _allNodes.FirstOrDefault(p => p.ID == selected);
            
            // Add null check - handle case where node isn't found
            if (_selected == null)
            {
                // Node not found in _allNodes - treat as no selection
                _selected = null;
                UpdateRequirements();
                UpdateUnlocks();
                SelectionScroll.Visible = false;
                NoSelectionBox.Visible = true;
                return;
            }
            
            if (_researchedNodes.Contains(selected.Value))
                ResearchButton.Text = Loc.GetString("research-tree-button-researched");

            if (_researchProgress.ContainsKey(selected.Value))
            {
                SelectedProgressLabel.Visible = true;
                SelectedProgressLabel.Text = Loc.GetString("research-tree-label-progress", ("progress", _researchProgress[selected.Value]), ("required", _selected.Cost));
            }

            UpdateRequirements();
            UpdateUnlocks();

            SelectionScroll.Visible = true;
            NoSelectionBox.Visible = false;

            ResearchButton.Disabled = !(_unlockedNodes.Contains(selected.Value) && !_researchedNodes.Contains(selected.Value));
            if (!ResearchButton.Disabled)
            {
                if (_queue.Contains(selected.Value))
                {
                    ResearchButton.Text = Loc.GetString("research-tree-button-remove-queue");
                    ResearchButton.OnPressed += RemoveNodeFromQueue;
                } else {
                    ResearchButton.Text = Loc.GetString("research-tree-button-research");
                    ResearchButton.OnPressed += ResearchNode;
                }
            }

            SelectedName.Text = Loc.GetString(_selected.Name);
            SelectedCost.Text = _selected.Cost.ToString();
        } else {
            _selected = null;
            UpdateRequirements();
            UpdateUnlocks();
            SelectionScroll.Visible = false;
            NoSelectionBox.Visible = true;
        }
    }

    private void QuickResearch(ProtoId<ResearchTreeNodePrototype> node) =>
        OnQuickResearch?.Invoke(node);

    private void ResearchNode(BaseButton.ButtonEventArgs args)
    {
        if (_selected != null && !_readonly)
            OnResearchButtonPressed?.Invoke(_selected.ID);
    }

    private void RemoveNodeFromQueue(BaseButton.ButtonEventArgs args)
    {
        if (_selected != null && !_readonly)
            OnRemoveQueueButtonPressed?.Invoke(_selected.ID);
    }

    private void UpdateQueue()
    {
        if (_queue.Count > 0)
        {
            QueueBox.RemoveAllChildren();
            var first = true;
            foreach (var nodeId in _queue)
            {
                if (!first)
                    QueueBox.AddChild(new Label(){Text = ">", Margin = new(10, 5)});
                else
                    first = false;
                
                var node = _protoMan.Index(nodeId);
                var button = new Button()
                {
                    Text = Loc.GetString(node.Name),
                    Margin = new(0, 5),
                };
                button.OnPressed += _ => TreeDisplay.Select(nodeId);
                QueueBox.AddChild(button);
                
            }
            NoQueueBox.Visible = false;
            QueueScroll.Visible = true;
        } else {
            NoQueueBox.Visible = true;
            QueueScroll.Visible = false;
        }
    }

    private void UpdateRequirements()
    {
        RequirementsBox.RemoveAllChildren();
        if (_selected == null)
            return;
        
        var tierProgress = "";
        if (!_unlockedTiers.Contains(_selected.Tier))
            tierProgress = " " + Loc.GetString("research-tree-requirement-progress", 
                ("progress", _researchedNodes.Sum(p => _protoMan.Index(p).Cost) + _researchProgress.Values.Sum()), 
                ("required", _protoMan.Index(_selected.Tier).UnlocksAt));
        var color = _unlockedTiers.Contains(_selected.Tier) ? Color.Green : Color.Red;
        var tierLabel = new RichTextLabel() { Text = $"[color={color.ToHex()}]- " + _protoMan.Index(_selected.Tier).Name + tierProgress + "[/color]"};
        RequirementsBox.AddChild(tierLabel);

        foreach(var req in _selected.Requires)
        {
            var reqProto = _protoMan.Index(req);
            var reqColor = _researchedNodes.Contains(req) ? Color.Green : Color.Red;
            var reqLabel = new RichTextLabel() { Text = $"[color={reqColor.ToHex()}]- " + Loc.GetString(reqProto.Name) + "[/color]"};
            RequirementsBox.AddChild(reqLabel);
        }
    }

    private void UpdateUnlocks()
    {
        UnlocksBox.RemoveAllChildren();
        if (_selected == null)
            return;

        foreach(var unlock in _selected.Unlocks)
        {
            var unlockProto = _protoMan.Index(unlock);
            if (unlockProto.Result == null)
                continue;
            
            var unlockName = _protoMan.Index<EntityPrototype>(unlockProto.Result).Name;
            var unlockLabel = new RichTextLabel() {Text = "- " + Loc.GetString(unlockName)};
            UnlocksBox.AddChild(unlockLabel);
        }

        foreach(var flag in _selected.UnlockFlags)
        {
            var flagProto = _protoMan.Index(flag);
            var unlockLabel = new RichTextLabel() {Text = "- " + Loc.GetString(flagProto.Text)};
            UnlocksBox.AddChild(unlockLabel);
        }
    }
}