using Content.Client.UserInterface.Controls;
using Content.Shared.MedicalScanner;
using Content.Shared.MedicalScannerPlus;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Carpmosia.HealthAnalyzer.UI;

[GenerateTypedNameReferences]
public sealed partial class HealthAnalyzerPlusWindow : FancyWindow
{
    public HealthAnalyzerPlusWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void Populate(HealthAnalyzerPlusScannedUserMessage msg)
    {
        HealthAnalyzerPlus.Populate(msg.State);
    }
}
