# Base loadouts to define common names and limits
- type: loadoutGroup
  id: BaseHead
  abstract: true
  name: loadout-group-base-head
  minLimit: 0

- type: loadoutGroup
  id: BaseGlasses
  abstract: true
  name: loadout-group-base-glasses
  minLimit: 0

- type: loadoutGroup
  id: BaseMask
  abstract: true
  name: loadout-group-base-mask
  minLimit: 0

- type: loadoutGroup
  id: BaseNeck
  abstract: true
  name: loadout-group-base-neck
  minLimit: 0

- type: loadoutGroup
  id: BaseGloves
  abstract: true
  name: loadout-group-base-gloves
  minLimit: 0

- type: loadoutGroup
  id: BaseJumpsuit
  abstract: true
  name: loadout-group-base-jumpsuit
  minLimit: 1

- type: loadoutGroup
  id: BaseBackpack
  abstract: true
  name: loadout-group-base-backpack
  minLimit: 1

- type: loadoutGroup
  id: BasePDA
  abstract: true
  name: loadout-group-base-pda
  minLimit: 1

- type: loadoutGroup
  id: BaseBelt
  abstract: true
  name: loadout-group-base-belt
  minLimit: 1

- type: loadoutGroup
  id: BaseOuterClothing
  abstract: true
  name: loadout-group-base-outerclothing
  minLimit: 0

- type: loadoutGroup
  id: BaseShoes
  abstract: true
  name: loadout-group-base-shoes
  minLimit: 0
  defaultSelected: 1

- type: loadoutGroup
  id: BaseSpecial
  abstract: true
  name: loadout-group-base-special
  minLimit: 0

- type: loadoutGroup
  id: BaseTrinkets
  abstract: true
  name: loadout-group-base-trinkets
  minLimit: 0
