- type: roleLoadout
  id: JobAtmosphericTechnician
  groups:
  - GroupTankHarness
  # Common groups
  - ClownHead
  - AtmosphericTechnicianGlasses
  # - AtmosphericTechnicianMask
  - AtmosphericTechnicianNeck
  # - AtmosphericTechnicianGloves
  - AtmosphericTechnicianJumpsuit
  - ClownBackpack
  # - AtmosphericTechnicianPDA
  # - AtmosphericTechnicianBelt
  - AtmosphericTechnicianOuterClothing
  - ClownShoes
  # Backpack fills
  - SurvivalExtended
  - GroupSpeciesBreathTool
  # - AtmosphericTechnicianSpecial
  - AtmosphericTechnicianTrinkets
  - AtmosphericTechnicianPets
