- type: roleLoadout
  id: JobStationEngineer
  groups:
  - GroupTankHarness
  # Common groups
  - SharedClownHead
  - StationEngineerGlasses
  # - StationEngineerMask
  - StationEngineerNeck
  # - StationEngineerGloves
  - StationEngineerJumpsuit
  - SharedClownBackpack
  - StationEngineerPDA
  # - StationEngineerBelt
  - StationEngineerOuterClothing
  - SharedClownShoes
  # Backpack fills
  - SurvivalExtended
  - GroupSpeciesBreathTool
  # - StationEngineerSpecial
  - StationEngineerTrinkets
  - StationEngineerPets
