- type: roleLoadout
  id: JobTechnicalAssistant
  groups:
  - GroupTankHarness
  # Common groups
  - ClownHead
  - TechnicalAssistantGlasses
  # - TechnicalAssistantMask
  - TechnicalAssistantNeck
  # - TechnicalAssistantGloves
  - TechnicalAssistantJumpsuit
  - ClownBackpack
  # - TechnicalAssistantPDA
  # - TechnicalAssistantBelt
  # - TechnicalAssistantOuterClothing
  - ClownShoes
  # Backpack fills
  - SurvivalExtended
  - GroupSpeciesBreathTool
  # - TechnicalAssistantSpecial
  - TechnicalAssistantTrinkets
  - TechnicalAssistantPets
