- type: roleLoadout
  id: JobTechnicalAssistant
  groups:
  - GroupTankHarness
  # Common groups
  - SharedClownHead
  - TechnicalAssistantGlasses
  # - TechnicalAssistantMask
  - TechnicalAssistantNeck
  # - TechnicalAssistantGloves
  - TechnicalAssistantJumpsuit
  - SharedClownBackpack
  # - TechnicalAssistantPDA
  # - TechnicalAssistantBelt
  # - TechnicalAssistantOuterClothing
  - SharedClownShoes
  # Backpack fills
  - SurvivalExtended
  - GroupSpeciesBreathTool
  # - TechnicalAssistantSpecial
  - TechnicalAssistantTrinkets
  - TechnicalAssistantPets
