- type: roleLoadout
  id: JobResearchAssistant
  groups:
  - GroupTankHarness
  # Common groups
  - SharedClownHead
  - ResearchAssistantGlasses
  # - ResearchAssistantMask
  - ResearchAssistantNeck
  # - ResearchAssistantGloves
  - ResearchAssistantJumpsuit
  - SharedClownBackpack
  # - ResearchAssistantPDA
  # - ResearchAssistantBelt
  # - ResearchAssistantOuterClothing
  - SharedClownShoes
  # Backpack fills
  - Survival
  - GroupSpeciesBreathTool
  # - ResearchAssistantSpecial
  - ResearchAssistantTrinkets
  - ResearchAssistantPets
