- type: roleLoadout
  id: JobResearchAssistant
  groups:
  - GroupTankHarness
  # Common groups
  - ClownHead
  - ResearchAssistantGlasses
  # - ResearchAssistantMask
  - ResearchAssistantNeck
  # - ResearchAssistantGloves
  - ResearchAssistantJumpsuit
  - ClownBackpack
  # - ResearchAssistantPDA
  # - ResearchAssistantBelt
  # - ResearchAssistantOuterClothing
  - ClownShoes
  # Backpack fills
  - Survival
  - GroupSpeciesBreathTool
  # - ResearchAssistantSpecial
  - ResearchAssistantTrinkets
  - ResearchAssistantPets
