- type: roleLoadout
  id: JobScientist
  groups:
  - GroupTankHarness
  # Common groups
  - SharedClownHead
  - ScientistGlasses
  # - ScientistMask
  - ScientistNeck
  - ScientistGloves
  - ScientistJumpsuit
  - SharedClownBackpack
  - ScientistPDA
  # - ScientistBelt
  - ScientistOuterClothing
  - SharedClownShoes
  # Backpack fills
  - Survival
  - GroupSpeciesBreathTool
  # - ScientistSpecial
  - ScientistTrinkets
  - ScientistPets
