- type: roleLoadout
  id: JobReporter
  groups:
  - GroupTankHarness
  # Common groups
  # - ReporterHead
  - ReporterGlasses
  # - ReporterMask
  # - ReporterNeck
  # - ReporterGloves
  - ReporterJumpsuit
  - ReporterBackpack
  # - ReporterPDA
  # - ReporterBelt
  # - ReporterOuterClothing
  # - ReporterShoes
  # Backpack fills
  - ReporterSurvival
  - GroupSpeciesBreathTool
  # - ReporterSpecial
  - ReporterTrinkets
