using System.Numerics;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Player;
using Robust.Shared.Prototypes;

namespace Content.Client._Offbrand.Surgery;

[GenerateTypedNameReferences]
public sealed partial class SurgicalDollPanel : FancyWindow
{
    public SurgicalDollPanel()
    {
        RobustXamlLoader.Load(this);
    }
}
