using System.Numerics;
using Content.Client._Offbrand.BodyVisuals;
using Content.Shared._Offbrand.Analyzers;
using Content.Shared.Humanoid;
using Content.Shared.IdentityManagement;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using static Robust.Client.UserInterface.Controls.BoxContainer;

namespace Content.Client._Offbrand.Surgery;

[GenerateTypedNameReferences]
public sealed partial class SurgicalDollPanelControl : BoxContainer
{
    [Dependency] private IEntityManager _entity = default!;
    [Dependency] private IPrototypeManager _prototype = default!;

    public SurgicalDollPanelControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void Update(EntityUid? target)
    {

        var doll = new _Offbrand.BodyVisuals.OffbrandHealthDollControl
            {
                OverrideDirection = Direction.South,
                SetSize = new Vector2(128, 128),
                Scale = new Vector2(4, 4),
                HorizontalAlignment = HAlignment.Center,
            };

        doll.SetBody(target);
        PatientView.AddChild(doll);
    }
}
