using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.MappingMenu;

[GenerateTypedNameReferences]
public sealed partial class MappingMenuWindow : DefaultWindow
{
    public MappingMenuWindow()
    {
        RobustXamlLoader.Load(this);

        for (int i = 1; i <= 5; i++)
        {
            var box = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal };

            box.AddChild(new Label { Text = $"{i}" });

            var c = new PanelContainer();
            c.StyleClasses.Add("LowDivider");
            box.AddChild(c);

            var g = new GridContainer { Rows = 3 };

            for (int b = 1; b <= 5; b++)
            {
                g.AddChild(new Button { Text = $"{i} - {b}" });
            }
            box.AddChild(g);


            Content.AddChild(box);
        }
    }
}
