using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.MappingMenu;

[GenerateTypedNameReferences]
public sealed partial class MappingMenuWindow : DefaultWindow
{
    private static readonly (string, int, string[])[] Buttons = [
    ("Walls", 2, [
        "WallSolidDiagonal", "WallReinforcedDiagonal",
        "WallSolid", "WallReinforced"
    ]),
    ("Windows", 3, [
        "GrilleDiagonal", "WindowDiagonal", "ReinforcedWindowDiagonal",
        "Grille", "Window", "ReinforcedWindow",
    ]),
    ("Pipes", 2, [
        "GasPipeTJunction",  "GasPipeBend",
        "GasPipeFourway", "GasPipeStraight",
    ]),
    ("Atmos", 2, [
        "GasVentPump",  "GasVentScrubber",
        "AirAlarm"
    ]),
    ("Atmos", 2, [
        "CableApcExtension",  "CableMV",
        "CableHV", "APCBasic"
    ]),
    ("Light", 2, [
        "Poweredlight",  "PoweredSmallLight",
    ]),
    ("Nothing", 2, [
        "ChairOfficeDark", "WaterCooler", "Chair", "Rack", "WeldingFuelTankFull", "WaterTankFull", "ComfyChair"
    ]),
    ("Nothing", 2, [
        "RailingCorner", "Railing", "RailingRound", "RailingCornerSmall"
    ]),
    ("Nothing", 2, [
        "DisposalPipe", "DisposalBend",
        "DisposalRouter", "DisposalJunction",
        "DisposalRouterFlipped", "DisposalJunctionFlipped",
        "DisposalUnit", "MailingUnit","DisposalTrunk",
    ])
    ];

    public MappingMenuWindow()
    {
        RobustXamlLoader.Load(this);

        foreach ((var section, var cols, var items) in Buttons)
        {
            var box = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical };

            box.AddChild(new Label { Text = section });

            var c = new PanelContainer();
            c.StyleClasses.Add("LowDivider");
            box.AddChild(c);

            var g = new GridContainer { Columns = cols };

            foreach (string item in items)
            {
                var but = new ContainerButton { };
                var ent = new EntityPrototypeView
                {
                    MinSize = new Vector2(64, 64),
                    Scale = new Vector2(2, 2),
                    MaxSize = new Vector2(64, 64),
                    Name = item
                };
                ent.SetPrototype(item);
                but.AddChild(ent);
                g.AddChild(but);
            }
            box.AddChild(g);


            Content.AddChild(box);
        }
    }
}
