- type: gameMapPool
  id: DefaultMapPool
  maps:
  # - CarpAmber
  # - CarpFeint
  - CarpLampocteis
  # - CarpOasis
  # - CarpPacked
  # - CarpSaltern
  # - CarpSparks
  # - CarpBagel
  # - CarpBox
  # - CarpElkridge
  # - CarpFland
  # - CarpMarathon
  # - CarpPlasma
  # - CarpExo
  # - CarpSnowball

- type: gameMapPool
  id: DefaultTerminalPool
  maps:
  - TerminalDonkRestStop
