- type: entity
  abstract: true
  parent: BaseRoomMarker
  id: BasePrefabMarker
  name: Prefab room marker
  components:
  - type: RoomFill
    rotation: false
    inheritRotation: true
  - type: Sprite
    sprite: _Carpmosia/Markers/room.rsi
    layers:
      - state: arrow

- type: entity
  abstract: true
  parent: BasePrefabMarker
  id: BasePrefabCenterMarker
  name: Prefab department marker
  components:
  - type: RoomFill
    rotation: true
    inheritRotation: false
    maxSize: 55, 55
    offset: 0, 0

- type: entity
  abstract: true
  parent: BasePrefabMarker
  id: BasePrefabLeftMarker
  name: Prefab department marker
  components:
  - type: RoomFill
    maxSize: 55, 55 # TODO
    offset: 0, 0 # TODO

- type: entity
  abstract: true
  parent: BasePrefabMarker
  id: BasePrefabRightMarker
  name: Prefab department marker
  components:
  - type: RoomFill
    maxSize: 55, 55 # TODO
    offset: 0, 0 # TODO
