- type: entity
  abstract: true
  parent: BaseRoomMarker
  id: BasePrefabMarker
  name: Prefab room marker
  components:
  - type: RoomFill
    rotation: false
    inheritRotation: true
  - type: Sprite
    sprite: _Carpmosia/Markers/room.rsi
    layers:
      - state: arrow

- type: entity
  abstract: true
  parent: BasePrefabMarker
  id: BasePrefabDepMarker
  name: Prefab department marker
  components:
  - type: RoomFill
    maxSize: 10, 10
    offset: 5, 5
