using Content.Shared._Offbrand.Analyzers;
using Content.Shared.Humanoid;
using Content.Shared.IdentityManagement;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Offbrand.Analyzer;

[GenerateTypedNameReferences]
public sealed partial class VitalsAnalyzerControl : BoxContainer
{
    [Dependency] private IEntityManager _entity = default!;
    [Dependency] private IPrototypeManager _prototype = default!;

    public VitalsAnalyzerControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void Update((VitalsData, EntityUid, bool)? scan)
    {
        if (scan is not var (data, target, updating))
        {
            NoPatientPlaceholder.Visible = true;
            MainContent.Visible = false;
            return;
        }

        NoPatientPlaceholder.Visible = false;
        MainContent.Visible = true;

        PatientView.SetEntity(target);
        PatientView.Visible = updating;
        OutOfRange.Visible = !updating;

        MainContent.Modulate =
            updating
                ? Color.White
                : Color.White.WithAlpha(0.4f);

        NameLabel.Text = Identity.Name(target, _entity);
        SpeciesLabel.Text =
            _entity.TryGetComponent<HumanoidProfileComponent>(target,
                out var humanoidComponent)
                ? Loc.GetString(_prototype.Index(humanoidComponent.Species).Name)
                : Loc.GetString("health-analyzer-window-entity-unknown-species-text");

        SpO2Label.Text = Loc.GetString(data.Spo2Name);
        SpO2Value.Text = Loc.GetString("offbrand-vitals-spo2-value", ("value", $"{data.Spo2 * 100:F0}"));

        if (data.Spo2 < 0.95)
            SpO2Value.FontColorOverride = Color.Yellow;

        if (data.Spo2 <= 0.5)
            SpO2Value.FontColorOverride = Color.Red;

        BrainActivityValue.Text = Loc.GetString("offbrand-vitals-brain-activity-value", ("value", $"{data.BrainHealth * 100:F0}"));

        if (data.BrainHealth < 0.95)
            BrainActivityValue.FontColorOverride = Color.Yellow;

        if (data.BrainHealth <= 0.5)
            BrainActivityValue.FontColorOverride = Color.Red;

        RespiratoryRateValue.Text = Loc.GetString("offbrand-vitals-respiratory-rate-value", ("value", data.RespiratoryRate));

        EtCO2Label.Text = Loc.GetString(data.Etco2Name);
        EtCO2Value.Text = Loc.GetString("offbrand-vitals-etco2-value", ("value", data.Etco2));

        var (systolic, diastolic) = data.BloodPressure;
        BloodPressureValue.Text = Loc.GetString("offbrand-vitals-blood-pressure-value", ("systolic", systolic), ("diastolic", diastolic));
        BloodVolumeValue.Text = Loc.GetString("offbrand-vitals-blood-volume-value", ("value", $"{data.BloodLevel * 100:F0}"));

        HeartRateValue.Text = Loc.GetString("offbrand-vitals-heart-rate-value", ("value", data.HeartRate));
        RadThresholdState.Text = GetThresholdText(data.RadThreshold);
        RadValue.Text = Loc.GetString("offbrand-vitals-rads-value", ("value", $"{Math.Round(data.Rads, 1)}"));
    }

    private string GetThresholdText(string threshold)
    {
        var state = "Normal";
        switch (threshold)
        {
            case "StatusEffectMinorRadSickness":
                state = "Minor Radiation Sickness";
                break;
            case "StatusEffectModerateRadSickness":
                RadThresholdState.FontColorOverride = Color.Yellow;
                state = "Moderate Radiation Sickness";
                break;
            case "StatusEffectSevereRadSickness":
                RadThresholdState.FontColorOverride = Color.Red;
                state = "Severe Radiation Sickness";
                break;
            default:
                break;
        }

        return Loc.GetString("offbrand-vitals-rads-state", ("state", state));
    }
}
