- type: species
  abstract: true
  id: BaseVoices
  voices:
  - FemaleAvali
  - FemaleDwarf
  - FemaleReptilian
  - FemaleSlime
  - FemaleTajaran
  - FemaleVulpkanin
  - MaleAvali
  - MaleReptilian
  - MaleSlime
  - MaleTajaran
  - MaleVulpkanin
  - UnisexArachnid
  - UnisexDiona
  - UnisexDwarf
  - UnisexMoth
  - UnisexVox
