# - type: loadoutGroup
#   id: HeadOfSecurityHead
#   parent: [BaseHead, CommonHead]

# - type: loadoutGroup
#   id: HeadOfSecurityGlasses
#   parent: [BaseGlasses, CommonGlasses]

# - type: loadoutGroup
#   id: HeadOfSecurityMask
#   parent: [BaseMask, CommonMask]

# - type: loadoutGroup
#   id: HeadOfSecurityNeck
#   parent: [BaseNeck, CommonNeck]

# - type: loadoutGroup
#   id: HeadOfSecurityGloves
#   parent: [BaseGloves, CommonGloves]

# - type: loadoutGroup
#   id: HeadOfSecurityJumpsuit
#   parent: [BaseJumpsuit, CommonJumpsuit]

# - type: loadoutGroup
#   id: HeadOfSecurityBackpack
#   parent: [BaseBackpack, CommonBackpack]

# - type: loadoutGroup
#   id: HeadOfSecurityPDA
#   parent: [BasePDA, CommonPDA]

# - type: loadoutGroup
#   id: HeadOfSecurityBelt
#   parent: [BaseBelt, CommonBelt]

# - type: loadoutGroup
#   id: HeadOfSecurityOuterClothing
#   parent: [BaseOuterClothing, CommonOuterClothing]

# - type: loadoutGroup
#   id: HeadOfSecurityShoes
#   parent: [BaseShoes, CommonShoes]

# - type: loadoutGroup
#   id: HeadOfSecuritySpecial
#   parent: [BaseSpecialSpecial, CommonSpecialSpecial]

# - type: loadoutGroup
#   id: HeadOfSecurityTrinkets
#   parent: [BaseTrinkets, CommonTrinkets]