- type: loadoutGroup
  parent: [ SecurityHead, CommonHead ]
  id: HeadOfSecurityHead
  loadouts:
  - HeadofSecurityHead
  - HeadofSecurityBeret

- type: loadoutGroup
  parent: [ SecurityGlasses, CommonGlasses ]
  id: HeadOfSecurityGlasses
  defaultSelected: 1

# - type: loadoutGroup
#   parent: [ SecurityMask, CommonMask ]
#   id: HeadOfSecurityMask

- type: loadoutGroup
  parent: [ SecurityNeck, CommonNeck ]
  id: HeadOfSecurityNeck
  loadouts:
  - HeadofSecurityCloak
  - HeadofSecurityMantle

# - type: loadoutGroup
#   parent: [ SecurityGloves, CommonGloves ]
#   id: HeadOfSecurityGloves

- type: loadoutGroup
  parent: [ SecurityJumpsuit, CommonJumpsuit ]
  id: HeadOfSecurityJumpsuit
  loadouts:
  - HeadofSecurityJumpsuit
  - HeadofSecurityJumpskirt
  - HeadofSecurityTurtleneck
  - HeadofSecurityTurtleneckSkirt
  - HeadofSecurityFormalSuit
  - HeadofSecurityFormalSkirt

- type: loadoutGroup
  parent: [ SecurityBackpack, CommonBackpack ]
  id: HeadOfSecurityBackpack

# - type: loadoutGroup
#   parent: [ SecurityPDA, CommonPDA ]
#   id: HeadOfSecurityPDA

- type: loadoutGroup
  parent: [ SecurityBelt, CommonBelt ]
  id: HeadOfSecurityBelt

- type: loadoutGroup
  parent: [ SecurityOuterClothing, CommonOuterClothing ]
  id: HeadOfSecurityOuterClothing
  minLimit: 1
  loadouts:
  - HeadofSecurityCoat
  - HeadofSecurityWinterCoat

- type: loadoutGroup
  parent: [ CommonShoes, SecurityShoes ]
  id: HeadOfSecurityShoes

# - type: loadoutGroup
#   parent: BaseSpecial
#   id: HeadOfSecuritySpecial

- type: loadoutGroup
  parent: [ SecurityTrinkets, CommonTrinkets ]
  id: HeadOfSecurityTrinkets
