- type: roleLoadout
  id: JobBartender
  groups:
  - GroupTankHarness
  # Common groups
  - ClownHead
  - BartenderGlasses
  # - BartenderMask
  - BartenderNeck
  # - BartenderGloves
  - BartenderJumpsuit
  - ClownBackpack
  # - BartenderPDA
  # - BartenderBelt
  - BartenderOuterClothing
  - ClownShoes
  # Backpack fills
  - Survival
  - GroupSpeciesBreathTool
  - BartenderSpecial
  - BartenderTrinkets
  - BartenderPets
