- type: roleLoadout
  id: JobBotanist
  groups:
  - GroupTankHarness
  # Common groups
  - SharedClownHead
  - BotanistGlasses
  # - BotanistMask
  - BotanistNeck
  # - BotanistGloves
  - BotanistJumpsuit
  - SharedClownBackpack
  # - BotanistPDA
  # - BotanistBelt
  - BotanistOuterClothing
  - SharedClownShoes
  # Backpack fills
  - Survival
  - GroupSpeciesBreathTool
  # - BotanistSpecial
  - BotanistTrinkets
  - BotanistPets
