- type: roleLoadout
  id: JobChaplain
  groups:
  - GroupTankHarness
  # Common groups
  - ChaplainHead
  - ChaplainGlasses
  - ChaplainMask
  - ChaplainNeck
  # - ChaplainGloves
  - ChaplainJumpsuit
  - ChaplainBackpack
  # - ChaplainPDA
  # - ChaplainBelt
  - ChaplainOuterClothing
  # - ChaplainShoes
  # Backpack fills
  - ChaplainSurvival
  - GroupSpeciesBreathTool
  - ChaplainSpecial
  - ChaplainTrinkets
