- type: roleLoadout
  id: JobChef
  groups:
  - GroupTankHarness
  # Common groups
  - SharedClownHead
  - ChefGlasses
  - ChefMask
  - ChefNeck
  # - ChefGloves
  - ChefJumpsuit
  - SharedClownBackpack
  # - ChefPDA
  # - ChefBelt
  - ChefOuterClothing
  - SharedClownShoes
  # Backpack fills
  - Survival
  - GroupSpeciesBreathTool
  # - ChefSpecial
  - ChefTrinkets
  - ChefPets
