- type: roleLoadout
  id: JobClown
  groups:
  # - GroupTankHarness
  # Common groups
  # - ClownHead
  # - ClownGlasses
  # - ClownMask
  # - ClownNeck
  # - ClownGloves
  # - ClownJumpsuit
  # - ClownBackpack
  # - ClownPDA
  # - ClownBelt
  # - ClownOuterClothing
  # - ClownShoes
  # Backpack fills
  # - Survival
  # - GroupSpeciesBreathTool
  # - ClownSpecial
  # - ClownTrinkets
