- type: roleLoadout
  id: JobClown
  canCustomizeName: true
  groups:
  - GroupTankHarness
  # Common groups
  - SharedClownHead
  - ClownGlasses
  # - ClownMask
  - ClownNeck
  # - ClownGloves
  - ClownJumpsuit
  - SharedClownBackpack
  # - ClownPDA
  # - ClownBelt
  - ClownOuterClothing
  - SharedClownShoes
  # Backpack fills
  - SurvivalClown
  # - GroupSpeciesBreathTool
  - ClownSpecial
  - ClownTrinkets
  - ClownPets
