- type: roleLoadout
  id: JobJanitor
  groups:
  - GroupTankHarness
  # Common groups
  - ClownHead
  - JanitorGlasses
  # - JanitorMask
  - JanitorNeck
  - JanitorGloves
  - JanitorJumpsuit
  - ClownBackpack
  # - JanitorPDA
  # - JanitorBelt
  - JanitorOuterClothing
  - ClownShoes
  # Backpack fills
  - Survival
  - GroupSpeciesBreathTool
  - JanitorSpecial
  - JanitorTrinkets
  - JanitorPets
