- type: roleLoadout
  id: JobJanitor
  groups:
  - GroupTankHarness
  # Common groups
  - JanitorHead
  - JanitorGlasses
  # - JanitorMask
  # - JanitorNeck
  - JanitorGloves
  - JanitorJumpsuit
  - JanitorBackpack
  # - JanitorPDA
  # - JanitorBelt
  - JanitorOuterClothing
  # - JanitorShoes
  # Backpack fills
  - JanitorSurvival
  - GroupSpeciesBreathTool
  - JanitorSpecial
  - JanitorTrinkets
