- type: roleLoadout
  id: JobJanitor
  groups:
  - GroupTankHarness
  # Common groups
  - SharedClownHead
  - JanitorGlasses
  # - JanitorMask
  - JanitorNeck
  - JanitorGloves
  - JanitorJumpsuit
  - SharedClownBackpack
  # - JanitorPDA
  # - JanitorBelt
  - JanitorOuterClothing
  - SharedClownShoes
  # Backpack fills
  - Survival
  - GroupSpeciesBreathTool
  - JanitorSpecial
  - JanitorTrinkets
  - JanitorPets
