- type: roleLoadout
  id: JobLawyer
  canCustomizeName: true
  groups:
  - GroupTankHarness
  # Common groups
  - SharedClownHead
  - LawyerGlasses
  # - LawyerMask
  - LawyerNeck
  # - LawyerGloves
  - LawyerJumpsuit
  - SharedClownBackpack
  # - LawyerPDA
  # - LawyerBelt
  # - LawyerOuterClothing
  - SharedClownShoes
  # Backpack fills
  - Survival
  - GroupSpeciesBreathTool
  # - LawyerSpecial
  - LawyerTrinkets
  - LawyerPets
