- type: roleLoadout
  id: JobLibrarian
  groups:
  - GroupTankHarness
  # Common groups
  - SharedClownHead
  - LibrarianGlasses
  # - LibrarianMask
  - LibrarianNeck
  # - LibrarianGloves
  - LibrarianJumpsuit
  - SharedClownBackpack
  # - LibrarianPDA
  # - LibrarianBelt
  # - LibrarianOuterClothing
  - SharedClownShoes
  # Backpack fills
  - Survival
  - GroupSpeciesBreathTool
  # - LibrarianSpecial
  - LibrarianTrinkets
  - LibrarianPets
