- type: roleLoadout
  id: JobLibrarian
  groups:
  - GroupTankHarness
  # Common groups
  - ClownHead
  - LibrarianGlasses
  # - LibrarianMask
  - LibrarianNeck
  # - LibrarianGloves
  - LibrarianJumpsuit
  - ClownBackpack
  # - LibrarianPDA
  # - LibrarianBelt
  # - LibrarianOuterClothing
  - ClownShoes
  # Backpack fills
  - Survival
  - GroupSpeciesBreathTool
  # - LibrarianSpecial
  - LibrarianTrinkets
  - LibrarianPets
