- type: roleLoadout
  id: JobMime
  groups:
  # - GroupTankHarness
  # Common groups
  # - MimeHead
  # - MimeGlasses
  # - MimeMask
  # - MimeNeck
  # - MimeGloves
  # - MimeJumpsuit
  # - MimeBackpack
  # - MimePDA
  # - MimeBelt
  # - MimeOuterClothing
  # - MimeShoes
  # Backpack fills
  # - Survival
  # - GroupSpeciesBreathTool
  # - MimeSpecial
  # - MimeTrinkets