- type: roleLoadout
  id: JobMusician
  canCustomizeName: true
  groups:
  - GroupTankHarness
  # Common groups
  - SharedClownHead
  - MusicianGlasses
  # - MusicianMask
  - MusicianNeck
  # - MusicianGloves
  - MusicianJumpsuit
  - SharedClownBackpack
  # - MusicianPDA
  # - MusicianBelt
  - MusicianOuterClothing
  - SharedClownShoes
  # Backpack fills
  - Survival
  - GroupSpeciesBreathTool
  - MusicianSpecial
  - MusicianTrinkets
  - MusicianPets
