- type: roleLoadout
  id: JobPassenger
  groups:
  - GroupTankHarness
  # Common groups
  - SharedClownHead
  - PassengerGlasses
  - PassengerMask
  - PassengerNeck
  - PassengerGloves
  - PassengerJumpsuit
  - SharedClownBackpack
  # - PassengerPDA
  # - PassengerBelt
  - PassengerOuterClothing
  - SharedClownShoes
  # Backpack fills
  - Survival
  - GroupSpeciesBreathTool
  # - PassengerSpecial
  - PassengerTrinkets
  - PassengerPets
