- type: roleLoadout
  id: JobPassenger
  groups:
  - GroupTankHarness
  # Common groups
  - ClownHead
  - PassengerGlasses
  - PassengerMask
  - PassengerNeck
  - PassengerGloves
  - PassengerJumpsuit
  - ClownBackpack
  # - PassengerPDA
  # - PassengerBelt
  - PassengerOuterClothing
  - ClownShoes
  # Backpack fills
  - Survival
  - GroupSpeciesBreathTool
  # - PassengerSpecial
  - PassengerTrinkets
  - PassengerPets
