- type: roleLoadout
  id: JobReporter
  canCustomizeName: true
  groups:
  - GroupTankHarness
  # Common groups
  - SharedClownHead
  - ReporterGlasses
  # - ReporterMask
  - ReporterNeck
  # - ReporterGloves
  - ReporterJumpsuit
  - SharedClownBackpack
  # - ReporterPDA
  # - ReporterBelt
  - ReporterOuterClothing
  - SharedClownShoes
  # Backpack fills
  - Survival
  - GroupSpeciesBreathTool
  # - ReporterSpecial
  - ReporterTrinkets
  - ReporterPets
