- type: roleLoadout
  id: JobServiceWorker
  groups:
  - GroupTankHarness
  # Common groups
  - SharedClownHead
  - ServiceWorkerGlasses
  # - ServiceWorkerMask
  - ServiceWorkerNeck
  # - ServiceWorkerGloves
  - ServiceWorkerJumpsuit
  - SharedClownBackpack
  # - ServiceWorkerPDA
  # - ServiceWorkerBelt
  # - ServiceWorkerOuterClothing
  - SharedClownShoes
  # Backpack fills
  - Survival
  - GroupSpeciesBreathTool
  # - ServiceWorkerSpecial
  - ServiceWorkerTrinkets
  - ServiceWorkerPets
