- type: roleLoadout
  id: JobTramDriver
  groups:
  - GroupTankHarness
  # Common groups
  - TramDriverHead
  - TramDriverGlasses
  # - TramDriverMask
  - TramDriverNeck
  - TramDriverGloves
  - TramDriverJumpsuit
  - TramDriverBackpack
  # - TramDriverPDA
  # - TramDriverBelt
  - TramDriverOuterClothing
  - TramDriverShoes
  # Backpack fills
  - Survival
  - GroupSpeciesBreathTool
  # - TramDriverSpecial
  - TramDriverTrinkets
  - TramDriverPets
