- type: roleLoadout
  id: JobBrigmedic
  groups:
  # - GroupTankHanress
  # Common groups
  - BrigmedicHead
  - BrigmedicGlasses
  # - BrigmedicMask
  # - BrigmedicNeck
  - BrigmedicGloves
  - BrigmedicJumpsuit
  - BrigmedicBackpack
  # - BrigmedicPDA
  # - BrigmedicBelt
  - BrigmedicOuterClothing
  - BrigmedicShoes
  # Backpack fills
  - SurvivalSecurity
  - GroupSpeciesBreathToolSecurity
  # - BrigmedicSpecial
  - BrigmedicTrinkets
  - BrigmedicPets
