- type: roleLoadout
  id: JobDetective
  groups:
  # - GroupTankHarness
  # Common groups
  - SharedClownHead
  - DetectiveGlasses
  # - DetectiveMask
  - DetectiveNeck
  # - DetectiveGloves
  - DetectiveJumpsuit
  - SharedClownBackpack
  # - DetectivePDA
  # - DetectiveBelt
  - DetectiveOuterClothing
  - SharedClownShoes
  # Backpack fills
  - SurvivalSecurity
  - GroupSpeciesBreathToolSecurity
  # - DetectiveSpecial
  - DetectiveTrinkets
  - DetectivePets
