- type: roleLoadout
  id: JobDetective
  groups:
  # - GroupTankHarness
  # Common groups
  - DetectiveHead
  # - DetectiveGlasses
  # - DetectiveMask
  - DetectiveNeck
  # - DetectiveGloves
  - DetectiveJumpsuit
  - DetectiveBackpack
  # - DetectivePDA
  # - DetectiveBelt
  - DetectiveOuterClothing
  - DetectiveShoes
  # Backpack fills
  - DetectiveSurvival
  - GroupSpeciesBreathToolSecurity
  # - DetectiveSpecial
  - DetectiveTrinkets
