- type: roleLoadout
  id: JobSecurityOfficer
  groups:
  # - GroupTankHarness
  # Common groups
  - ClownHead
  - SecurityOfficerGlasses
  # - SecurityOfficerMask
  - SecurityOfficerNeck
  # - SecurityOfficerGloves
  - SecurityOfficerJumpsuit
  - ClownBackpack
  - SecurityOfficerPDA
  - SecurityOfficerBelt
  - SecurityOfficerOuterClothing
  - ClownShoes
  # Backpack fills
  - SurvivalSecurity
  - GroupSpeciesBreathToolSecurity
  # - SecurityOfficerSpecial
  - SecurityOfficerTrinkets
  - SecurityOfficerPets
