- type: roleLoadout
  id: JobCaptain
  groups:
  # - GroupTankHarness
  # Common groups
  - ClownHead
  - CaptainGlasses
  # - CaptainMask
  - CaptainNeck
  # - CaptainGloves
  - CaptainJumpsuit
  - ClownBackpack
  # - CaptainPDA
  # - CaptainBelt
  - CaptainOuterClothing
  - ClownShoes
  # Backpack fills
  - Survival
  - GroupSpeciesBreathTool
  # - CaptainSpecial
  - CaptainTrinkets
  - CaptainPets
