- type: roleLoadout
  id: JobChiefEngineer
  groups:
  - GroupTankHarness
  # Common groups
  - ClownHead
  - ChiefEngineerGlasses
  # - ChiefEngineerMask
  - ChiefEngineerNeck
  # - ChiefEngineerGloves
  - ChiefEngineerJumpsuit
  - ClownBackpack
  # - ChiefEngineerPDA
  # - ChiefEngineerBelt
  - ChiefEngineerOuterClothing
  - ClownShoes
  # Backpack fills
  - SurvivalExtended
  - GroupSpeciesBreathTool
  # - ChiefEngineerSpecial
  - ChiefEngineerTrinkets
  - ChiefEngineerPets
