- type: roleLoadout
  id: JobChiefEngineer
  groups:
  - GroupTankHarness
  # Common groups
  - SharedClownHead
  - ChiefEngineerGlasses
  # - ChiefEngineerMask
  - ChiefEngineerNeck
  # - ChiefEngineerGloves
  - ChiefEngineerJumpsuit
  - SharedClownBackpack
  # - ChiefEngineerPDA
  # - ChiefEngineerBelt
  - ChiefEngineerOuterClothing
  - SharedClownShoes
  # Backpack fills
  - SurvivalExtended
  - GroupSpeciesBreathTool
  # - ChiefEngineerSpecial
  - ChiefEngineerTrinkets
  - ChiefEngineerPets
