- type: roleLoadout
  id: JobHeadOfPersonnel
  groups:
  - GroupTankHarness
  # Common groups
  - ClownHead
  - ClownHeadOfPersonnelGlasses
  # - ClownHeadOfPersonnelMask
  - ClownHeadOfPersonnelNeck
  # - ClownHeadOfPersonnelGloves
  - ClownHeadOfPersonnelJumpsuit
  - ClownBackpack
  # - ClownHeadOfPersonnelPDA
  # - ClownHeadOfPersonnelBelt
  - ClownHeadOfPersonnelOuterClothing
  - ClownShoes
  # Backpack fills
  - Survival
  - GroupSpeciesBreathTool
  # - ClownHeadOfPersonnelSpecial
  - ClownHeadOfPersonnelTrinkets
  - ClownHeadOfPersonnelPets
