- type: roleLoadout
  id: JobHeadOfSecurity
  groups:
  # - GroupTankHarness
  # Common groups
  - SharedClownHead
  - SharedClownHeadOfSecurityGlasses
  # - SharedClownHeadOfSecurityMask
  - SharedClownHeadOfSecurityNeck
  # - SharedClownHeadOfSecurityGloves
  - SharedClownHeadOfSecurityJumpsuit
  - SharedClownBackpack
  # - SharedClownHeadOfSecurityPDA
  - SharedClownHeadOfSecurityBelt
  - SharedClownHeadOfSecurityOuterClothing
  - SharedClownShoes
  # Backpack fills
  - SurvivalSecurity
  - GroupSpeciesBreathToolSecurity
  # - SharedClownHeadOfSecuritySpecial
  - SharedClownHeadOfSecurityTrinkets
  - SharedClownHeadOfSecurityPets
