- type: roleLoadout
  id: JobHeadOfPersonnel
  groups:
  - GroupTankHarness
  # Common groups
  - SharedClownHead
  - SharedClownHeadOfPersonnelGlasses
  # - SharedClownHeadOfPersonnelMask
  - SharedClownHeadOfPersonnelNeck
  # - SharedClownHeadOfPersonnelGloves
  - SharedClownHeadOfPersonnelJumpsuit
  - SharedClownBackpack
  # - SharedClownHeadOfPersonnelPDA
  # - SharedClownHeadOfPersonnelBelt
  - SharedClownHeadOfPersonnelOuterClothing
  - SharedClownShoes
  # Backpack fills
  - Survival
  - GroupSpeciesBreathTool
  # - SharedClownHeadOfPersonnelSpecial
  - SharedClownHeadOfPersonnelTrinkets
  - SharedClownHeadOfPersonnelPets
