- type: roleLoadout
  id: JobHeadOfSecurity
  groups:
  # - GroupTankHarness
  # Common groups
  - ClownHead
  - ClownHeadOfSecurityGlasses
  # - ClownHeadOfSecurityMask
  - ClownHeadOfSecurityNeck
  # - ClownHeadOfSecurityGloves
  - ClownHeadOfSecurityJumpsuit
  - ClownBackpack
  # - ClownHeadOfSecurityPDA
  - ClownHeadOfSecurityBelt
  - ClownHeadOfSecurityOuterClothing
  - ClownShoes
  # Backpack fills
  - SurvivalSecurity
  - GroupSpeciesBreathToolSecurity
  # - ClownHeadOfSecuritySpecial
  - ClownHeadOfSecurityTrinkets
  - ClownHeadOfSecurityPets
