- type: roleLoadout
  id: JobHeadOfSecurity
  groups:
  # - GroupTankHarness
  # Common groups
  - SharedClownHead
  - HeadOfSecurityGlasses
  # - HeadOfSecurityMask
  - HeadOfSecurityNeck
  # - HeadOfSecurityGloves
  - HeadOfSecurityJumpsuit
  - SharedClownBackpack
  # - HeadOfSecurityPDA
  - HeadOfSecurityBelt
  - HeadOfSecurityOuterClothing
  - SharedClownShoes
  # Backpack fills
  - SurvivalSecurity
  - GroupSpeciesBreathToolSecurity
  # - HeadOfSecuritySpecial
  - HeadOfSecurityTrinkets
  - HeadOfSecurityPets
