- type: roleLoadout
  id: JobQuartermaster
  groups:
  - GroupTankHarness
  # Common groups
  - ClownHead
  - QuartermasterGlasses
  # - QuartermasterMask
  - QuartermasterNeck
  # - QuartermasterGloves
  - QuartermasterJumpsuit
  - ClownBackpack
  # - QuartermasterPDA
  # - QuartermasterBelt
  - QuartermasterOuterClothing
  - ClownShoes
  # Backpack fills
  - Survival
  - GroupSpeciesBreathTool
  # - QuartermasterSpecial
  - QuartermasterTrinkets
  - QuartermasterPets
