- type: roleLoadout
  id: JobQuartermaster
  groups:
  - GroupTankHarness
  # Common groups
  - SharedClownHead
  - QuartermasterGlasses
  # - QuartermasterMask
  - QuartermasterNeck
  # - QuartermasterGloves
  - QuartermasterJumpsuit
  - SharedClownBackpack
  # - QuartermasterPDA
  # - QuartermasterBelt
  - QuartermasterOuterClothing
  - SharedClownShoes
  # Backpack fills
  - Survival
  - GroupSpeciesBreathTool
  # - QuartermasterSpecial
  - QuartermasterTrinkets
  - QuartermasterPets
