- type: roleLoadout
  id: JobResearchDirector
  groups:
  - GroupTankHarness
  # Common groups
  - ClownHead
  - ResearchDirectorGlasses
  # - ResearchDirectorMask
  - ResearchDirectorNeck
  - ResearchDirectorGloves
  - ResearchDirectorJumpsuit
  - ClownBackpack
  # - ResearchDirectorPDA
  # - ResearchDirectorBelt
  - ResearchDirectorOuterClothing
  - ClownShoes
  # Backpack fills
  - Survival
  - GroupSpeciesBreathTool
  # - ResearchDirectorSpecial
  - ResearchDirectorTrinkets
  - ResearchDirectorPets
