name: Self Approve

on:
  pull_request:

jobs:
  self-approve:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Self-Approve
        uses: nicklegan/github-repo-self-approve-action@v1.0.1
        with:
          appid: ${{ secrets.APPID }}
          privatekey: ${{ secrets.PRIVATEKEY }}
          installationid: ${{ secrets.INSTALLATIONID }}
