- type: roleLoadout
  id: JobCargoTechnician
  groups:
  - GroupTankHarness
  # Common groups
  - SharedClownHead
  - CargoTechnicianGlasses
  # - CargoTechnicianMask
  - CargoTechnicianNeck
  # - CargoTechnicianGloves
  - CargoTechnicianJumpsuit
  - SharedClownBackpack
  - CargoTechnicianPDA
  # - CargoTechnicianBelt
  - CargoTechnicianOuterClothing
  - SharedClownShoes
  # Backpack fills
  - Survival
  - GroupSpeciesBreathTool
  # - CargoTechnicianSpecial
  - CargoTechnicianTrinkets
  - CargoTechnicianPets
