- type: roleLoadout
  id: JobQuartermaster
  groups:
  - GroupTankHarness
  # Common groups
  - QuartermasterHead
  - QuartermasterGlasses
  # - QuartermasterMask
  - QuartermasterNeck
  # - QuartermasterGloves
  - QuartermasterJumpsuit
  - QuartermasterBackpack
  # - QuartermasterPDA
  # - QuartermasterBelt
  - QuartermasterOuterClothing
  - QuartermasterShoes
  # Backpack fills
  - QuartermasterSurvival
  - GroupSpeciesBreathTool
  # - QuartermasterSpecial
  - QuartermasterTrinkets
